# Introduction to Python & Jupyter Notebook
# 1_Intro_to_Python.ipynb
## Defining Variables

In [38]:
"Hello World"

'Hello World'

In [39]:
greeting = "Hello World" # this is a string variable (<- this is a comment)

In [40]:
greeting

'Hello World'

In [41]:
greeting = "Hello World!!!"
greeting

'Hello World!!!'

In [42]:
print(greeting)

Hello World!!!


## Basic Math

Define two variables

In [ ]:
a = 2
b = 15

Get the sum

In [ ]:
a + b

In [ ]:
my_sum = a + b # get sum of a & b

In [ ]:
# print sum 
my_sum

Get the product

In [ ]:
my_product = a * b 
my_product

In [ ]:
a-b

In [ ]:
a/b

In [ ]:
b % a

In [ ]:
a**b

# Import libraries

numpy - Numerical Python _(http://numpy.org)_

In [1]:
import numpy as np

Define a numpy array

In [2]:
ages_list = [25, 30, 35, 40, 45] # this is a Python list

In [3]:
ages = np.array(ages_list) # this is a numpy array

In [4]:
ages_list

[25, 30, 35, 40, 45]

In [5]:
ages

array([25, 30, 35, 40, 45])

In [6]:
ages + 2

array([27, 32, 37, 42, 47])

In [7]:
ages_list + 2

TypeError: can only concatenate list (not "int") to list

In [8]:
ages * 2

array([50, 60, 70, 80, 90])

In [9]:
ages_list * 2

[25, 30, 35, 40, 45, 25, 30, 35, 40, 45]

In [10]:
# you can also do this in a single line
ages = np.array([25, 30, 35, 40, 45, 50, 55])
ages

array([25, 30, 35, 40, 45, 50, 55])

Get specific elements - note that in Python, the index starts from 0

In [11]:
ages[0]

25

In [12]:
ages[6]

55

In [13]:
ages[6]

55

In [14]:
ages[-1] # this is the last element

55

In [15]:
ages[-2]

50

Get subset of elements, based on index range

In [16]:
ages[0:4] # goes from index = 0 to 3 (first 4 elements)

array([25, 30, 35, 40])

In [17]:
ages[:4] # goes from beginning to index 3 (same result as above)

array([25, 30, 35, 40])

In [18]:
ages[1:4] # goes from index = 1 to 3 (2nd to 4th elements)

array([30, 35, 40])

In [19]:
ages[1:] # goes from index = 1 to last element (same result as above)

array([30, 35, 40, 45, 50, 55])

In [20]:
ages[:] # goes from first to last element (same as ages)

array([25, 30, 35, 40, 45, 50, 55])

In [21]:
ages[::2] # keeps every 2nd element only

array([25, 35, 45, 55])

In [22]:
ages[::3] 

array([25, 40, 55])

In [23]:
ages[::-1] # reverses order of elements

array([55, 50, 45, 40, 35, 30, 25])

Get subset of elements, based on a condition

In [24]:
ages[ages<40]

array([25, 30, 35])

In [25]:
ages[ages<=40]

array([25, 30, 35, 40])

In [27]:
ages

array([25, 30, 35, 40, 45, 50, 55])

In [26]:
[ages<=40]

[array([ True,  True,  True,  True, False, False, False])]

In [28]:
ages[(ages>40) & ((ages % 10)==0)]

array([50])

In [29]:
ages[(ages>40) | ((ages % 10)==0)]

array([30, 40, 45, 50, 55])

In [30]:
ages[(ages>25) & (ages<40)]

array([30, 35])

Get no. of elements / length of array

In [31]:
len(ages)

7

Get the mean, minimum, and maximum

In [32]:
ages_mean = np.mean(ages)
ages_mean

40.0

In [33]:
np.min(ages)

25

In [34]:
np.max(ages)

55

In [35]:
np.std(ages)

10.0

In [36]:
np.median(ages)

40.0